---
# Tareas para consultar usuarios en Microsoft Graph
- name: Obtener token de acceso de Azure AD
  uri:
    url: "{{ graph_auth_url }}/{{ tenant_id }}/oauth2/v2.0/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: client_credentials
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret }}"
      scope: "https://graph.microsoft.com/.default"
    status_code: 200
  register: auth_response
  no_log: true

- name: Consulta específica por UPN (búsqueda exacta)
  block:
    - name: Consultar usuario específico por UPN
      uri:
        url: "{{ graph_api_url }}/users/{{ filters.upn_exact }}"
        method: GET
        headers:
          Authorization: "Bearer {{ auth_response.json.access_token }}"
        status_code: [200, 404]
      register: specific_user_response

    - name: Procesar usuario encontrado por UPN
      set_fact:
        queried_users: "{{ [specific_user_response.json] if specific_user_response.status == 200 else [] }}"

  when: filters.upn_exact is defined and filters.upn_exact != ""

- name: Consulta con filtros generales
  block:
    - name: Inicializar componentes de query
      set_fact:
        search_components: []
        filter_components: []

    - name: Añadir búsqueda por nombre/email
      set_fact:
        search_components: "{{ search_components + ['displayName:' + filters.search_term] }}"
      when: filters.search_term is defined and filters.search_term != ""

    - name: Añadir filtro por departamento
      set_fact:
        filter_components: "{{ filter_components + ['department eq \\'' + filters.department + '\\''] }}"
      when: filters.department is defined and filters.department != ""

    - name: Añadir filtro por estado habilitado
      set_fact:
        filter_components: "{{ filter_components + ['accountEnabled eq ' + filters.enabled] }}"
      when: filters.enabled is defined and filters.enabled != ""

    - name: Construir query string final
      set_fact:
        query_parts: []

    - name: Añadir componente de búsqueda
      set_fact:
        query_parts: '{{ query_parts + [''$search="'' + search_components | join('' OR '') + ''"''] }}'
      when: search_components | length > 0

    - name: Añadir componente de filtro
      set_fact:
        query_parts: "{{ query_parts + ['$filter=' + filter_components | join(' and ')] }}"
      when: filter_components | length > 0

    - name: Construir URL de consulta final
      set_fact:
        final_query_string: "{{ query_parts | join('&') if query_parts | length > 0 else '' }}"

    - name: Consultar usuarios en Microsoft 365
      uri:
        url: "{{ graph_api_url }}/users{% if final_query_string %}?{{ final_query_string }}{% endif %}"
        method: GET
        headers:
          Authorization: "Bearer {{ auth_response.json.access_token }}"
          ConsistencyLevel: eventual
        status_code: 200
      register: query_users_response

    - name: Procesar usuarios encontrados
      set_fact:
        queried_users: "{{ query_users_response.json.value }}"

  when: filters.upn_exact is not defined or filters.upn_exact == ""

- name: Validar resultado de la consulta
  fail:
    msg: "Usuario no encontrado: {{ filters.upn_exact }}"
  when:
    - filters.upn_exact is defined
    - filters.upn_exact != ""
    - queried_users | length == 0

- name: Mostrar cantidad de usuarios encontrados
  debug:
    msg: "Se encontraron {{ queried_users | length }} usuarios"
