---
- name: Crear usuarios en Microsoft 365 (AWX-friendly)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tenant_id: "{{ lookup('env','TENANT_ID') | default(vault_tenant_id | default('your-tenant-id'), true) }}"
    client_id: "{{ lookup('env','CLIENT_ID') | default(vault_client_id | default('your-client-id'), true) }}"
    client_secret: "{{ lookup('env','CLIENT_SECRET') | default(vault_client_secret | default('your-client-secret'), true) }}"

    # Estas variables las rellenará el Survey:
    display_name: "{{ display_name }}"
    user_principal_name: "{{ user_upn }}"
    mail_nickname: "{{ mail_nickname }}"
    password: "{{ temp_password }}"
    force_change_password: "{{ force_password | default(true) | bool }}"
    department: "{{ department | default('') }}"
    job_title: "{{ job_title | default('') }}"

  tasks:
    - name: Validar obligatorios
      assert:
        that:
          - display_name | length > 0
          - user_principal_name | length > 0
          - mail_nickname | length > 0
          - password | length >= 8
        fail_msg: "Faltan campos requeridos o no cumplen requisitos."

    - name: Crear usuario mediante Microsoft Graph API
      include_role:
        name: microsoft_graph_user
      vars:
        action: create
        user_data:
          display_name: "{{ display_name }}"
          user_principal_name: "{{ user_principal_name }}"
          mail_nickname: "{{ mail_nickname }}"
          password: "{{ password }}"
          force_change_password: "{{ force_change_password }}"
          department: "{{ department }}"
          job_title: "{{ job_title }}"
      tags: [create_users, users]
