---
# Playbook interactivo para eliminar usuarios en Microsoft 365
# Este playbook solicita el usuario a eliminar interactivamente
name: Eliminar usuarios en Microsoft 365
hosts: localhost
connection: local
gather_facts: false

vars:
  tenant_id: "{{ vault_tenant_id | default('your-tenant-id') }}"
  client_id: "{{ vault_client_id | default('your-client-id') }}"
  client_secret: "{{ vault_client_secret | default('your-client-secret') }}"

tasks:
  - name: Advertencia sobre eliminación de usuarios
    debug:
      msg: |
        
        ⚠️  ADVERTENCIA: ELIMINACIÓN DE USUARIO ⚠️
        
        Esta operación eliminará PERMANENTEMENTE el usuario de Microsoft 365.
        
        - Se perderán todos los datos asociados al usuario
        - El acceso a todos los servicios será revocado inmediatamente  
        - Esta acción NO se puede deshacer
        
        Proceda solo si está completamente seguro de esta acción.

  - name: Solicitar UPN del usuario a eliminar
    pause:
      prompt: |
        
        === ELIMINAR USUARIO DE MICROSOFT 365 ===
        
        User Principal Name del usuario a eliminar (ej. usuario@tuempresa.com)
        
        ESCRIBA "CANCELAR" para abortar la operación
    register: upn_input

  - name: Verificar cancelación
    meta: end_play
    when: (upn_input.user_input | trim | lower) == 'cancelar'

  - name: Validar UPN ingresado
    fail:
      msg: "Error: Debe ingresar un User Principal Name válido"
    when: upn_input.user_input | trim == ""

  - name: Verificar existencia del usuario
    include_role:
      name: microsoft_graph_user
    vars:
      action: query
      filters:
        search_term: "{{ upn_input.user_input | trim }}"
        upn_exact: "{{ upn_input.user_input | trim }}"

  - name: Solicitar confirmación con texto específico
    pause:
      prompt: |
        
        === CONFIRMACIÓN REQUERIDA ===
        
        Usuario a eliminar: {{ upn_input.user_input | trim }}
        
        Para confirmar la eliminación, escriba exactamente: ELIMINAR USUARIO
        
        Cualquier otro texto cancelará la operación
    register: confirmation_text

  - name: Verificar texto de confirmación
    fail:
      msg: "Operación cancelada: El texto de confirmación no coincide"
    when: (confirmation_text.user_input | trim) != "ELIMINAR USUARIO"

  - name: Segunda confirmación de seguridad
    pause:
      prompt: |
        
        === ÚLTIMA CONFIRMACIÓN ===
        
        ¿Está ABSOLUTAMENTE SEGURO de que desea eliminar el usuario {{ upn_input.user_input | trim }}?
        
        Esta es la ÚLTIMA oportunidad para cancelar.
        
        Escriba "SI, ELIMINAR" para proceder, cualquier otro texto cancelará
    register: final_confirmation

  - name: Verificar confirmación final
    fail:
      msg: "Operación cancelada por el usuario"
    when: (final_confirmation.user_input | trim) != "SI, ELIMINAR"

  - name: Eliminar usuario mediante Microsoft Graph API
    include_role:
      name: microsoft_graph_user
    vars:
      action: delete
      user_principal_name: "{{ upn_input.user_input | trim }}"
    tags:
      - delete_users
      - users

  - name: Mostrar confirmación de eliminación
    debug:
      msg: |
        
        ✅ USUARIO ELIMINADO EXITOSAMENTE
        
        Usuario: {{ upn_input.user_input | trim }}
        Fecha/Hora: {{ ansible_date_time.iso8601 }}
        
        El usuario ha sido eliminado permanentemente del tenant.
