---
# Playbook para eliminar usuarios en Microsoft 365 (AWX-friendly)
- name: Eliminar usuarios en Microsoft 365
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tenant_id: "{{ lookup('env','TENANT_ID') | default(vault_tenant_id | default('your-tenant-id'), true) }}"
    client_id: "{{ lookup('env','CLIENT_ID') | default(vault_client_id | default('your-client-id'), true) }}"
    client_secret: "{{ lookup('env','CLIENT_SECRET') | default(vault_client_secret | default('your-client-secret'), true) }}"

    # El Survey pedirá 'target_user_upn' (solo la parte a la izquierda de @)
    # Normalizamos: a minúsculas, espacios -> '.', y quitamos caracteres no permitidos
    target_upn_normalized: "{{ target_user_upn | lower }}"
    target_user_principal_name: "{{ target_upn_normalized }}@{{ m365_domain | default('contoso.com') }}"

    # Variable de confirmación del Survey
    confirm_deletion: "{{ confirm_deletion | default(false) | bool }}"

  tasks:
    - name: Validar que se especificó usuario target
      assert:
        that:
          - target_upn_normalized | length > 0
        fail_msg: "Debe especificar el usuario a eliminar (target_user_upn)."

    - name: Verificar confirmación de eliminación
      fail:
        msg: "La eliminación debe ser confirmada explícitamente mediante el Survey."
      when: not confirm_deletion

    - name: Verificar existencia del usuario
      include_role:
        name: microsoft_graph_user
      vars:
        action: query
        filters:
          upn_exact: "{{ target_user_principal_name }}"

    - name: Mostrar información del usuario a eliminar
      debug:
        msg: |
          ⚠️  ATENCIÓN: Se eliminará el usuario {{ target_user_principal_name }}
          Esta operación es IRREVERSIBLE.

    - name: Eliminar usuario mediante Microsoft Graph API
      include_role:
        name: microsoft_graph_user
      vars:
        action: delete
        user_principal_name: "{{ target_user_principal_name }}"
      tags: [delete_users, users]

    - name: Confirmar eliminación completada
      debug:
        msg: |
          ✅ Usuario {{ target_user_principal_name }} eliminado exitosamente.
          Fecha/Hora: {{ ansible_date_time.iso8601 }}