---
# Playbook para actualizar usuarios en Microsoft 365 (AWX-friendly)
- name: Actualizar usuarios en Microsoft 365
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tenant_id: "{{ lookup('env','TENANT_ID') | default(vault_tenant_id | default('your-tenant-id'), true) }}"
    client_id: "{{ lookup('env','CLIENT_ID') | default(vault_client_id | default('your-client-id'), true) }}"
    client_secret: "{{ lookup('env','CLIENT_SECRET') | default(vault_client_secret | default('your-client-secret'), true) }}"

    # El Survey pedirá 'target_user_upn' (solo la parte a la izquierda de @)
    # Normalizamos: a minúsculas, espacios -> '.', y quitamos caracteres no permitidos
    target_upn_normalized: "{{ target_user_upn | lower }}"
    target_user_principal_name: "{{ target_upn_normalized }}@{{ m365_domain | default('contoso.com') }}"

    # Variables que serán rellenadas por el Survey (opcionales para updates):
    new_display_name: "{{ new_display_name | default('') }}"
    new_department: "{{ new_department | default('') }}"
    new_job_title: "{{ new_job_title | default('') }}"
    new_office_location: "{{ new_office_location | default('') }}"
    new_phone_number: "{{ new_phone_number | default('') }}"
    new_street_address: "{{ new_street_address | default('') }}"

  tasks:
    - name: Validar que se especificó usuario target
      assert:
        that:
          - target_upn_normalized | length > 0
        fail_msg: "Debe especificar el usuario a actualizar (target_user_upn)."

    - name: Verificar usuario existente
      include_role:
        name: microsoft_graph_user
      vars:
        action: query
        filters:
          upn_exact: "{{ target_user_principal_name }}"

    - name: Construir objeto de actualizaciones
      set_fact:
        user_updates: {}

    - name: Añadir nombre completo a actualizaciones
      set_fact:
        user_updates: "{{ user_updates | combine({'displayName': new_display_name}) }}"
      when: new_display_name != ""

    - name: Añadir departamento a actualizaciones
      set_fact:
        user_updates: "{{ user_updates | combine({'department': new_department}) }}"
      when: new_department != ""

    - name: Añadir puesto de trabajo a actualizaciones
      set_fact:
        user_updates: "{{ user_updates | combine({'jobTitle': new_job_title}) }}"
      when: new_job_title != ""

    - name: Añadir ubicación de oficina a actualizaciones
      set_fact:
        user_updates: "{{ user_updates | combine({'officeLocation': new_office_location}) }}"
      when: new_office_location != ""

    - name: Añadir teléfono a actualizaciones
      set_fact:
        user_updates: "{{ user_updates | combine({'businessPhones': [new_phone_number]}) }}"
      when: new_phone_number != ""

    - name: Añadir dirección a actualizaciones
      set_fact:
        user_updates: "{{ user_updates | combine({'streetAddress': new_street_address}) }}"
      when: new_street_address != ""

    - name: Verificar si hay actualizaciones
      fail:
        msg: "No se han especificado campos para actualizar. Operación cancelada."
      when: user_updates | length == 0

    - name: Actualizar usuario mediante Microsoft Graph API
      include_role:
        name: microsoft_graph_user
      vars:
        action: update
        user_principal_name: "{{ target_user_principal_name }}"
        user_updates: "{{ user_updates }}"
      tags: [update_users, users]